version: '3'

services:
  postgres:
    image: postgres:14-alpine
    container_name: postgres_gin_gonic_api
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: root
      POSTGRES_DB: gin-gonic-api

volumes:
  postgres-data: